### ISSUE TITLE
Access the original JSON

### ISSUE THREAD

**Issue by sid** [Overcoat/Overcoat#17]
Is it possible to access the original JSON in the catalog? Specifying the resultKeyPath returns an array of the required objects in the responseObject but I need to set some meta info that was in the JSON outside the key path for the objects.

**Comment by startupthekid** [comment]
I know this issue has been closed for a while but I was trying to achieve the same thing, access whatever metadata the API sends back and I've come up with a much easier solution. 

First make a subclass of `OVCResponse` and override `resultKeyPathForJSONDictionary:` to specify the result key path.

    + (NSString *)resultKeyPathForJSONDictionary:(NSDictionary *)JSONDictionary {
         return @"data";
    }

Next, override `responseWithHTTPResponse:JSONObject:resultClass:`. Since this method passes in the full JSON response, you can make a property, say `@property (nonatomic) NSDictionary *metadata` in the public interface of your `OVCResponse` subclass. Then just call `responseWithHTTPResponse:JSONObject:resultClass` on `super` like so:

    + (instancetype)responseWithHTTPResponse:(NSHTTPURLResponse *)HTTPResponse JSONObject:(id)JSONObject resultClass:(Class)resultClass {
        ApiResponse *response = [super responseWithHTTPResponse:HTTPResponse JSONObject:JSONObject resultClass:resultClass];
        response.metadata = JSONObject;
        return response;
    }

Easy as pie!
